apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
spec:
  replicas: 2  # Dvě instance Apache pro škálování
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:latest  # Použijeme oficiální Apache kontejner
        ports:
        - containerPort: 80
